
name: drug-search docker
on: 
  push: 
    branches: 
      - 'master'
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.11.0]
    steps:
      - uses: actions/checkout@v2
      - name: set up node and run npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: angular install
        run: npm install -g @angular/cli
      - name: angular build
        run: ng build
      - name: docker build
        run: docker build -t weifang993/drug-search .
      - name: docker login
        # run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}        
      - name: docker push
        run: docker push weifang993/drug-search