
name: drug-search docker
on: 
  push: 
    branches: 
      - 'master'
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: set up node and run npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: angular install
        run: npm install -g @angular/cli
      - name: angular build
        run: ng build --prod 
      - name: docker build
        run: docker build -t weifang993/drug-search .
      - name: docker login
        uses: docker/login-action@1
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: docker/cli@master
        with:
          args: push weifang993/drug-search